# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_detectGPUs <- function(platform_idx) {
    .Call('gpuR_cpp_detectGPUs', PACKAGE = 'gpuR', platform_idx)
}

#' @title Detect Number of Platforms
#' @description Find out how many OpenCL enabled platforms are available.
#' @return An integer value representing the number of platforms available.
#' @seealso \link{detectGPUs}
#' @export
detectPlatforms <- function() {
    .Call('gpuR_detectPlatforms', PACKAGE = 'gpuR')
}

cpp_gpuInfo <- function(platform_idx_, gpu_idx_) {
    .Call('gpuR_cpp_gpuInfo', PACKAGE = 'gpuR', platform_idx_, gpu_idx_)
}

cpp_gpu_two_vec <- function(A_, B_, C_, sourceCode_, kernel_function_) {
    .Call('gpuR_cpp_gpu_two_vec', PACKAGE = 'gpuR', A_, B_, C_, sourceCode_, kernel_function_)
}

rcpp_hello_world <- function() {
    .Call('gpuR_rcpp_hello_world', PACKAGE = 'gpuR')
}

